name: Build, Push, and Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sra-repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}
            mkdir -p /home/ec2-user/keys
            echo "${{ secrets.CLOUDFRONT_PRIVATE_KEY }}" > /home/ec2-user/keys/cloudfront_private_key.pem
            
            cat << EOF > /home/ec2-user/docker-compose.yml
            version: '3.8'
            services:
              app:
                image: ${{ steps.build-image.outputs.image }}
                ports:
                  - "9090:9090"
                environment:
                  # ================================================================
                  # = LINHA CORRIGIDA: ATIVA O PERFIL DE PRODUÇÃO                    =
                  # ================================================================
                  - SPRING_PROFILES_ACTIVE=prod
                  # BANCO DE DADOS E JWT
                  - DB_URL_PROD=${{ secrets.DB_URL_PROD }}
                  - DB_USERNAME_PROD=${{ secrets.DB_USERNAME_PROD }}
                  - DB_PASSWORD_PROD=${{ secrets.DB_PASSWORD_PROD }}
                  - JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
                  # APIS
                  - GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
                  - MERCADOPAGO_ACCESS_TOKEN=${{ secrets.MERCADOPAGO_ACCESS_TOKEN }}
                  # AWS
                  - AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}
                  - AWS_S3_REGION=${{ secrets.AWS_S3_REGION }}
                  - CLOUDFRONT_DOMAIN_NAME=${{ secrets.CLOUDFRONT_DOMAIN_NAME }}
                  - CLOUDFRONT_KEY_PAIR_ID=${{ secrets.CLOUDFRONT_KEY_PAIR_ID }}
                  - CLOUDFRONT_PRIVATE_KEY_PATH=/app/keys/cloudfront_private_key.pem
                  # DOMINIOS E REDIRECTS
                  - COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN }}
                  - APP_OAUTH2_REDIRECT_URI=${{ secrets.APP_OAUTH2_REDIRECT_URI }}
                  # E-MAIL
                  - MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
                  - MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
                  # OAUTH2
                  - GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
                  - GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
                  - GIT_CLIENT_ID=${{ secrets.GIT_CLIENT_ID }}
                  - GIT_CLIENT_SECRET=${{ secrets.GIT_CLIENT_SECRET }}
                  # ETC
                  - spring.jpa.hibernate.ddl-auto=update
                  - spring.jackson.time-zone=UTC
                  - server.port=9090
                volumes:
                  - /home/ec2-user/keys:/app/keys:ro
                restart: always
            EOF
            
            cd /home/ec2-user
            docker-compose pull
            docker-compose up -d --force-recreate